# Web Scraping with BeautifulSoup & Pandas

This notebook demonstrates how to extract, parse, and structure data from HTML using Python.

In [1]:
!pip install beautifulsoup4 lxml html5lib pandas requests

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.0.2)
Requirement already satisfied: html5lib in /usr/local/lib/python3.12/dist-packages (1.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.12/dist-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from html5lib) (0.5.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)

In [2]:
import warnings
warnings.simplefilter("ignore")

from bs4 import BeautifulSoup
import requests
import pandas as pd

## HTML Parsing and Navigation

This section explores how to navigate HTML using BeautifulSoup, including:
- Tags
- Children
- Parents
- Siblings

In [3]:
from IPython.display import HTML
HTML("""
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>
<h3><b id='boldest'>Lebron James</b></h3>
<p> Salary: $ 92,000,000 </p>
<h3> Stephen Curry</h3>
<p> Salary: $85,000, 000 </p>
<h3> Kevin Durant </h3>
<p> Salary: $73,200, 000</p>
</body>
</html>
""")

In [4]:
html = "<!DOCTYPE html><html><head><title>Page Title</title></head><body><h3><b id='boldest'>Lebron James</b></h3><p> Salary: $ 92,000,000 </p><h3> Stephen Curry</h3><p> Salary: $85,000, 000 </p><h3> Kevin Durant </h3><p> Salary: $73,200, 000</p></body></html>"

In [5]:
soup = BeautifulSoup(html, "html.parser")

In [6]:
print(soup.prettify())

<!DOCTYPE html>
<html>
 <head>
  <title>
   Page Title
  </title>
 </head>
 <body>
  <h3>
   <b id="boldest">
    Lebron James
   </b>
  </h3>
  <p>
   Salary: $ 92,000,000
  </p>
  <h3>
   Stephen Curry
  </h3>
  <p>
   Salary: $85,000, 000
  </p>
  <h3>
   Kevin Durant
  </h3>
  <p>
   Salary: $73,200, 000
  </p>
 </body>
</html>

In [7]:
tag_object = soup.title
print("tag object:", tag_object)
print("tag object type:", type(tag_object))

tag object: <title>Page Title</title>
tag object type: <class 'bs4.element.Tag'>

In [8]:
tag_object = soup.h3
tag_object

In [9]:
tag_child = tag_object.b
tag_child

In [10]:
parent_tag = tag_child.parent
parent_tag

In [11]:
tag_object.parent

### Navigating HTML Structure

Here we move through the HTML tree using:
- `.next_sibling`
- `.parent`
- `.children`

In [12]:
sibling_1 = tag_object.next_sibling
sibling_1

In [13]:
sibling_2 = sibling_1.next_sibling
sibling_2

In [14]:
stephen_salary = sibling_2.next_sibling
stephen_salary

In [15]:
print(stephen_salary.text)

 Salary: $85,000, 000

### Working with HTML Attributes

This section demonstrates how to extract attributes from HTML tags using:
- dictionary-style access
- `.attrs`
- `.get()`

In [16]:
tag_child['id']

'boldest'

In [17]:
tag_child.attrs

{'id': 'boldest'}

In [18]:
tag_child.get('id')

'boldest'

### Extracting Text Content

BeautifulSoup represents text using NavigableString objects.  
Here we extract and convert text into standard Python strings.

In [19]:
tag_string = tag_child.string
tag_string

'Lebron James'

In [20]:
type(tag_string)

bs4.element.NavigableString

In [21]:
unicode_string = str(tag_string)
unicode_string

'Lebron James'

## Extracting Data from HTML Tables

In this section, we work with structured HTML tables and learn how to:
- locate rows and columns
- iterate through table data
- extract structured values

In [22]:
from IPython.display import HTML
HTML("""
<table>
  <tr>
    <td id='flight' >Flight No</td>
    <td>Launch site</td>
    <td>Payload mass</td>
   </tr>
  <tr>
    <td>1</td>
    <td><a href='https://en.wikipedia.org/wiki/Florida'>Florida</a></td>
    <td>300 kg</td>
  </tr>
  <tr>
    <td>2</td>
    <td><a href='https://en.wikipedia.org/wiki/Texas'>Texas</a></td>
    <td>94 kg</td>
  </tr>
  <tr>
    <td>3</td>
    <td><a href='https://en.wikipedia.org/wiki/Florida'>Florida</a> </td>
    <td>80 kg</td>
  </tr>
</table>
""")

In [23]:
table = "<table><tr><td id='flight' >Flight No</td><td>Launch site</td><td>Payload mass</td></tr><tr><td>1</td><td><a href='https://en.wikipedia.org/wiki/Florida'>Florida</a></td><td>300 kg</td></tr><tr><td>2</td><td><a href='https://en.wikipedia.org/wiki/Texas'>Texas</a></td><td>94 kg</td></tr><tr><td>3</td><td><a href='https://en.wikipedia.org/wiki/Florida'>Florida</a> </td><td>80 kg</td></tr></table>"

In [24]:
table_bs = BeautifulSoup(table, "html.parser")

### Using find_all()

The `find_all()` method retrieves all matching elements in the HTML structure.

In [25]:
table_rows = table_bs.find_all('tr')
table_rows

[<tr><td id="flight">Flight No</td><td>Launch site</td><td>Payload mass</td></tr>,
 <tr><td>1</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a></td><td>300 kg</td></tr>,
 <tr><td>2</td><td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td><td>94 kg</td></tr>,
 <tr><td>3</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a> </td><td>80 kg</td></tr>]

In [26]:
first_row = table_rows[0]
first_row

In [27]:
print(type(first_row))

<class 'bs4.element.Tag'>

In [28]:
first_row.td

In [29]:
for i, row in enumerate(table_rows):
    print("row", i, "is", row)

row 0 is <tr><td id="flight">Flight No</td><td>Launch site</td><td>Payload mass</td></tr>
row 1 is <tr><td>1</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a></td><td>300 kg</td></tr>
row 2 is <tr><td>2</td><td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td><td>94 kg</td></tr>
row 3 is <tr><td>3</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a> </td><td>80 kg</td></tr>

In [30]:
for i, row in enumerate(table_rows):
    print("row", i)
    cells = row.find_all('td')
    for j, cell in enumerate(cells):
        print("column", j, "cell", cell)

row 0
column 0 cell <td id="flight">Flight No</td>
column 1 cell <td>Launch site</td>
column 2 cell <td>Payload mass</td>
row 1
column 0 cell <td>1</td>
column 1 cell <td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a></td>
column 2 cell <td>300 kg</td>
row 2
column 0 cell <td>2</td>
column 1 cell <td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td>
column 2 cell <td>94 kg</td>
row 3
column 0 cell <td>3</td>
column 1 cell <td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a> </td>
column 2 cell <td>80 kg</td>

In [31]:
list_input = table_bs.find_all(name=["tr", "td"])
list_input

[<tr><td id="flight">Flight No</td><td>Launch site</td><td>Payload mass</td></tr>,
 <td id="flight">Flight No</td>,
 <td>Launch site</td>,
 <td>Payload mass</td>,
 <tr><td>1</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a></td><td>300 kg</td></tr>,
 <td>1</td>,
 <td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a></td>,
 <td>300 kg</td>,
 <tr><td>2</td><td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td><td>94 kg</td></tr>,
 <td>2</td>,
 <td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td>,
 <td>94 kg</td>,
 <tr><td>3</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a> </td><td>80 kg</td></tr>,
 <td>3</td>,
 <td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a> </td>,
 <td>80 kg</td>]

In [32]:
table_bs.find_all(id="flight")

In [33]:
list_input = table_bs.find_all(href="https://en.wikipedia.org/wiki/Florida")
list_input

[<a href="https://en.wikipedia.org/wiki/Florida">Florida</a>,
 <a href="https://en.wikipedia.org/wiki/Florida">Florida</a>]

In [34]:
table_bs.find_all(href=True)

[<a href="https://en.wikipedia.org/wiki/Florida">Florida</a>,
 <a href="https://en.wikipedia.org/wiki/Texas">Texas</a>,
 <a href="https://en.wikipedia.org/wiki/Florida">Florida</a>]

In [35]:
table_bs.find_all(href=False)

[<table><tr><td id="flight">Flight No</td><td>Launch site</td><td>Payload mass</td></tr><tr><td>1</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a></td><td>300 kg</td></tr><tr><td>2</td><td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td><td>94 kg</td></tr><tr><td>3</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a> </td><td>80 kg</td></tr></table>,
 <tr><td id="flight">Flight No</td><td>Launch site</td><td>Payload mass</td></tr>,
 <td id="flight">Flight No</td>,
 <td>Launch site</td>,
 <td>Payload mass</td>,
 <tr><td>1</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a></td><td>300 kg</td></tr>,
 <td>1</td>,
 <td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a></td>,
 <td>300 kg</td>,
 <tr><td>2</td><td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td><td>94 kg</td></tr>,
 <td>2</td>,
 <td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td>,
 <td>94 kg</td>,
 <tr><td>3</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a> </td><td>80 kg</td></tr>,
 <td>3</td>,
 <td><a href="https://en.wikipedia.org/wiki/Florida">Florida</a> </td>,
 <td>80 kg</td>]

In [36]:
soup.find(id="boldest")

In [37]:
table_bs.find_all(string="Florida")

['Florida', 'Florida']

In [38]:
from IPython.display import HTML

HTML("""
<h3>Rocket Launch </h3>
<p>
<table class='rocket'>
  <tr>
    <td>Flight No</td>
    <td>Launch site</td>
    <td>Payload mass</td>
  </tr>
  <tr>
    <td>1</td>
    <td>Florida</td>
    <td>300 kg</td>
  </tr>
  <tr>
    <td>2</td>
    <td>Texas</td>
    <td>94 kg</td>
  </tr>
  <tr>
    <td>3</td>
    <td>Florida </td>
    <td>80 kg</td>
  </tr>
</table>
</p>

<h3>Pizza Party</h3>
<table class='pizza'>
  <tr>
    <td>Pizza Place</td>
    <td>Orders</td>
    <td>Slices</td>
  </tr>
  <tr>
    <td>Domino's Pizza</td>
    <td>10</td>
    <td>100</td>
  </tr>
  <tr>
    <td>Little Caesars</td>
    <td>12</td>
    <td>144</td>
  </tr>
  <tr>
    <td>Papa John's</td>
    <td>15</td>
    <td>165</td>
  </tr>
</table>
""")

In [39]:
two_tables = "<h3>Rocket Launch </h3><p><table class='rocket'><tr><td>Flight No</td><td>Launch site</td><td>Payload mass</td></tr><tr><td>1</td><td>Florida</td><td>300 kg</td></tr><tr><td>2</td><td>Texas</td><td>94 kg</td></tr><tr><td>3</td><td>Florida</td><td>80 kg</td></tr></table></p><p><h3>Pizza Party</h3><table class='pizza'><tr><td>Pizza Place</td><td>Orders</td><td>Slices</td></tr><tr><td>Domino's Pizza</td><td>10</td><td>100</td></tr><tr><td>Little Caesars</td><td>12</td><td>144</td></tr><tr><td>Papa John's</td><td>15</td><td>165</td></tr></table>"

In [40]:
two_tables_bs = BeautifulSoup(two_tables, "html.parser")

In [41]:
two_tables_bs.find("table")

<table class="rocket"><tr><td>Flight No</td><td>Launch site</td><td>Payload mass</td></tr><tr><td>1</td><td>Florida</td><td>300 kg</td></tr><tr><td>2</td><td>Texas</td><td>94 kg</td></tr><tr><td>3</td><td>Florida</td><td>80 kg</td></tr></table>

In [42]:
two_tables_bs.find("table", class_="pizza")

<table class="pizza"><tr><td>Pizza Place</td><td>Orders</td><td>Slices</td></tr><tr><td>Domino's Pizza</td><td>10</td><td>100</td></tr><tr><td>Little Caesars</td><td>12</td><td>144</td></tr><tr><td>Papa John's</td><td>15</td><td>165</td></tr></table>

In [43]:
url = "https://web.archive.org/web/20230224123642/https://www.ibm.com/us-en/"

In [44]:
data = requests.get(url).text

In [45]:
soup = BeautifulSoup(data, "html.parser")

## Scraping Links from a Web Page

This section extracts all hyperlinks (`<a>` tags) from a webpage.

In [46]:
for link in soup.find_all('a', href=True):
    print(link.get('href'))

https://web.archive.org/web/20230224123642/https://www.ibm.com/reports/threat-intelligence/
https://web.archive.org/web/20230224123642/https://www.ibm.com/about
https://web.archive.org/web/20230224123642/https://www.ibm.com/consulting/?lnk=flathl
https://web.archive.org/web/20230224123642/https://www.ibm.com/consulting/strategy/?lnk=flathl
https://web.archive.org/web/20230224123642/https://www.ibm.com/consulting/ibmix?lnk=flathl
https://web.archive.org/web/20230224123642/https://www.ibm.com/consulting/technology/
https://web.archive.org/web/20230224123642/https://www.ibm.com/consulting/operations/?lnk=flathl
https://web.archive.org/web/20230224123642/https://www.ibm.com/strategic-partnerships
https://web.archive.org/web/20230224123642/https://www.ibm.com/employment/?lnk=flatitem
https://web.archive.org/web/20230224123642/https://www.ibm.com/impact
https://web.archive.org/web/20230224123642/https://research.ibm.com/
https://web.archive.org/web/20230224123642/https://www.ibm.com/

## Scraping Images

Here we extract image sources (`src`) from all `<img>` tags.

In [47]:
for link in soup.find_all('img'):  # image tag = <img>
    print(link)
    print(link.get('src'))

<img alt="Person standing with arms crossed" aria-describedby="bx--image-1" class="bx--image__img" src="https://web.archive.org/web/20230224123642im_/https://1.dam.s81c.com/p/0a23e414312bcb6f/08196d0e04260ae5_cropped.jpg.global.sr_16x9.jpg"/>
https://web.archive.org/web/20230224123642im_/https://1.dam.s81c.com/p/0a23e414312bcb6f/08196d0e04260ae5_cropped.jpg.global.sr_16x9.jpg
<img alt="Team members at work in a conference room" aria-describedby="bx--image-2" class="bx--image__img" src="https://web.archive.org/web/20230224123642im_/https://1.dam.s81c.com/p/06655c075aa3aa29/CaitOppermann_2019_12_06_IBMGarage_DSC3304.jpg.global.m_16x9.jpg"/>
https://web.archive.org/web/20230224123642im_/https://1.dam.s81c.com/p/06655c075aa3aa29/CaitOppermann_2019_12_06_IBMGarage_DSC3304.jpg.global.m_16x9.jpg
<img alt="Coworkers looking at laptops" aria-describedby="bx--image-3" class="bx--image__img" src="https://web.archive.org/web/20230224123642im_/https://1.dam.s81c.com/p/08f951353c2707b8/052022_CaitOppermann_InsideIBM_London_2945_03.jpg.global.sr_16x9.jpg"/>
https://web.archive.org/web/20230224123642im_/https://1.dam.s81c.com/p/08f951353c2707b8/052022_CaitOppermann_InsideIBM_London_2945_03.jpg.global.sr_16x9.jpg
<img alt="Cloud developer with red sweater coding at desk" aria-describedby="bx--image-4" class="bx--image__img" src="https://web.archive.org/web/20230224123642im_/https://1.dam.s81c.com/p/064e0139f5a3aa5e/0500002_Lowell_LI_100119.jpg.global.sr_16x9.jpg"/>
https://web.archive.org/web/20230224123642im_/https://1.dam.s81c.com/p/064e0139f5a3aa5e/0500002_Lowell_LI_100119.jpg.global.sr_16x9.jpg
<img alt="Aerial view of automated conveyer belt and machinery at work" aria-describedby="bx--image-5" class="bx--image__img" src="https://web.archive.org/web/20230224123642im_/https://1.dam.s81c.com/p/0795cae91a25156f/conveyorrobottopview.jpg.global.sr_16x9.jpg"/>
https://web.archive.org/web/20230224123642im_/https://1.dam.s81c.com/p/0795cae91a25156f/conveyorrobottopview.jpg.global.sr_16x9.jpg
<img alt="Overhead view of partners collaborating on design with laptops and coffee" aria-describedby="bx--image-6" class="bx--image__img" src="https://web.archive.org/web/20230224123642im_/https://1.dam.s81c.com/p/06dfa9ccdba4ec79/1f417900-9042-44d1-9c219a854bbb62ea.jpg.global.sr_16x9.jpg"/>
https://web.archive.org/web/20230224123642im_/https://1.dam.s81c.com/p/06dfa9ccdba4ec79/1f417900-9042-44d1-9c219a854bbb62ea.jpg.global.sr_16x9.jpg

## Scraping Structured Data from Tables

We extract color names and corresponding hex codes from an HTML table.

In [48]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/datasets/HTMLColorCodes.html"

In [49]:
data = requests.get(url).text

In [50]:
soup = BeautifulSoup(data, "html.parser")

In [51]:
table = soup.find('table')
table

<table border="1" class="main-table">
<tr>
<td>Number </td>
<td>Color</td>
<td>Color Name</td>
<td>Hex Code<br/>#RRGGBB</td>
<td>Decimal Code<br/>(R,G,B)</td>
</tr>
<tr>
<td>1</td>
<td style="background:lightsalmon;"> </td>
<td>lightsalmon</td>
<td>#FFA07A</td>
<td>rgb(255,160,122)</td>
</tr>
<tr>
<td>2</td>
<td style="background:salmon;"> </td>
<td>salmon</td>
<td>#FA8072</td>
<td>rgb(250,128,114)</td>
</tr>
<tr>
<td>3</td>
<td style="background:darksalmon;"> </td>
<td>darksalmon</td>
<td>#E9967A</td>
<td>rgb(233,150,122)</td>
</tr>
<tr>
<td>4</td>
<td style="background:lightcoral;"> </td>
<td>lightcoral</td>
<td>#F08080</td>
<td>rgb(240,128,128)</td>
</tr>
<tr>
<td>5</td>
<td style="background:coral;"> </td>
<td>coral</td>
<td>#FF7F50</td>
<td>rgb(255,127,80)</td>
</tr>
<tr>
<td>6</td>
<td style="background:tomato;"> </td>
<td>tomato</td>
<td>#FF6347</td>
<td>rgb(255,99,71)</td>
</tr>
<tr>
<td>7</td>
<td style="background:orangered;"> </td>
<td>orangered</td>
<td>#FF4500</td>
<td>rgb(255,69,0)</td>
</tr>
<tr>
<td>8</td>
<td style="background:gold;"> </td>
<td>gold</td>
<td>#FFD700</td>
<td>rgb(255,215,0)</td>
</tr>
<tr>
<td>9</td>
<td style="background:orange;"> </td>
<td>orange</td>
<td>#FFA500</td>
<td>rgb(255,165,0)</td>
</tr>
<tr>
<td>10</td>
<td style="background:darkorange;"> </td>
<td>darkorange</td>
<td>#FF8C00</td>
<td>rgb(255,140,0)</td>
</tr>
<tr>
<td>11</td>
<td style="background:lightyellow;"> </td>
<td>lightyellow</td>
<td>#FFFFE0</td>
<td>rgb(255,255,224)</td>
</tr>
<tr>
<td>12</td>
<td style="background:lemonchiffon;"> </td>
<td>lemonchiffon</td>
<td>#FFFACD</td>
<td>rgb(255,250,205)</td>
</tr>
<tr>
<td>13</td>
<td style="background:papayawhip;"> </td>
<td>papayawhip</td>
<td>#FFEFD5</td>
<td>rgb(255,239,213)</td>
</tr>
<tr>
<td>14</td>
<td style="background:moccasin;"> </td>
<td>moccasin</td>
<td>#FFE4B5</td>
<td>rgb(255,228,181)</td>
</tr>
<tr>
<td>15</td>
<td style="background:peachpuff;"> </td>
<td>peachpuff</td>
<td>#FFDAB9</td>
<td>rgb(255,218,185)</td>
</tr>
<tr>
<td>16</td>
<td style="background:palegoldenrod;"> </td>
<td>palegoldenrod</td>
<td>#EEE8AA</td>
<td>rgb(238,232,170)</td>
</tr>
<tr>
<td>17</td>
<td style="background:khaki;"> </td>
<td>khaki</td>
<td>#F0E68C</td>
<td>rgb(240,230,140)</td>
</tr>
<tr>
<td>18</td>
<td style="background:darkkhaki;"> </td>
<td>darkkhaki</td>
<td>#BDB76B</td>
<td>rgb(189,183,107)</td>
</tr>
<tr>
<td>19</td>
<td style="background:yellow;"> </td>
<td>yellow</td>
<td>#FFFF00</td>
<td>rgb(255,255,0)</td>
</tr>
<tr>
<td>20</td>
<td style="background:lawngreen;"> </td>
<td>lawngreen</td>
<td>#7CFC00</td>
<td>rgb(124,252,0)</td>
</tr>
<tr>
<td>21</td>
<td style="background:chartreuse;"> </td>
<td>chartreuse</td>
<td>#7FFF00</td>
<td>rgb(127,255,0)</td>
</tr>
<tr>
<td>22</td>
<td style="background:limegreen;"> </td>
<td>limegreen</td>
<td>#32CD32</td>
<td>rgb(50,205,50)</td>
</tr>
<tr>
<td>23</td>
<td style="background:lime;"> </td>
<td>lime</td>
<td>#00FF00</td>
<td>rgb(0.255.0)</td>
</tr>
<tr>
<td>24</td>
<td style="background:forestgreen;"> </td>
<td>forestgreen</td>
<td>#228B22</td>
<td>rgb(34,139,34)</td>
</tr>
<tr>
<td>25</td>
<td style="background:green;"> </td>
<td>green</td>
<td>#008000</td>
<td>rgb(0,128,0)</td>
</tr>
<tr>
<td>26</td>
<td style="background:powderblue;"> </td>
<td>powderblue</td>
<td>#B0E0E6</td>
<td>rgb(176,224,230)</td>
</tr>
<tr>
<td>27</td>
<td style="background:lightblue;"> </td>
<td>lightblue</td>
<td>#ADD8E6</td>
<td>rgb(173,216,230)</td>
</tr>
<tr>
<td>28</td>
<td style="background:lightskyblue;"> </td>
<td>lightskyblue</td>
<td>#87CEFA</td>
<td>rgb(135,206,250)</td>
</tr>
<tr>
<td>29</td>
<td style="background:skyblue;"> </td>
<td>skyblue</td>
<td>#87CEEB</td>
<td>rgb(135,206,235)</td>
</tr>
<tr>
<td>30</td>
<td style="background:deepskyblue;"> </td>
<td>deepskyblue</td>
<td>#00BFFF</td>
<td>rgb(0,191,255)</td>
</tr>
<tr>
<td>31</td>
<td style="background:lightsteelblue;"> </td>
<td>lightsteelblue</td>
<td>#B0C4DE</td>
<td>rgb(176,196,222)</td>
</tr>
<tr>
<td>32</td>
<td style="background:dodgerblue;"> </td>
<td>dodgerblue</td>
<td>#1E90FF</td>
<td>rgb(30,144,255)</td>
</tr>
</table>

In [52]:
for row in table.find_all('tr'):  # each row
    cols = row.find_all('td')     # each column

    if len(cols) > 0:  # skip header row
        color_name = cols[2].string
        color_code = cols[3].string

        print("{} ---> {}".format(color_name, color_code))

Color Name ---> None
lightsalmon ---> #FFA07A
salmon ---> #FA8072
darksalmon ---> #E9967A
lightcoral ---> #F08080
coral ---> #FF7F50
tomato ---> #FF6347
orangered ---> #FF4500
gold ---> #FFD700
orange ---> #FFA500
darkorange ---> #FF8C00
lightyellow ---> #FFFFE0
lemonchiffon ---> #FFFACD
papayawhip ---> #FFEFD5
moccasin ---> #FFE4B5
peachpuff ---> #FFDAB9
palegoldenrod ---> #EEE8AA
khaki ---> #F0E68C
darkkhaki ---> #BDB76B
yellow ---> #FFFF00
lawngreen ---> #7CFC00
chartreuse ---> #7FFF00
limegreen ---> #32CD32
lime ---> #00FF00
forestgreen ---> #228B22
green ---> #008000
powderblue ---> #B0E0E6
lightblue ---> #ADD8E6
lightskyblue ---> #87CEFA
skyblue ---> #87CEEB
deepskyblue ---> #00BFFF
lightsteelblue ---> #B0C4DE
dodgerblue ---> #1E90FF

In [53]:
for row in table.find_all('tr'):
    cols = row.find_all('td')

    if len(cols) > 0:
        color_name = cols[2].text.strip()
        color_code = cols[3].text.strip()

        print(f"{color_name} ---> {color_code}")

Color Name ---> Hex Code#RRGGBB
lightsalmon ---> #FFA07A
salmon ---> #FA8072
darksalmon ---> #E9967A
lightcoral ---> #F08080
coral ---> #FF7F50
tomato ---> #FF6347
orangered ---> #FF4500
gold ---> #FFD700
orange ---> #FFA500
darkorange ---> #FF8C00
lightyellow ---> #FFFFE0
lemonchiffon ---> #FFFACD
papayawhip ---> #FFEFD5
moccasin ---> #FFE4B5
peachpuff ---> #FFDAB9
palegoldenrod ---> #EEE8AA
khaki ---> #F0E68C
darkkhaki ---> #BDB76B
yellow ---> #FFFF00
lawngreen ---> #7CFC00
chartreuse ---> #7FFF00
limegreen ---> #32CD32
lime ---> #00FF00
forestgreen ---> #228B22
green ---> #008000
powderblue ---> #B0E0E6
lightblue ---> #ADD8E6
lightskyblue ---> #87CEFA
skyblue ---> #87CEEB
deepskyblue ---> #00BFFF
lightsteelblue ---> #B0C4DE
dodgerblue ---> #1E90FF

In [54]:
import pandas as pd

## Real-World Web Scraping Example

In this section, we scrape data from Wikipedia and convert it into a structured dataset.

Steps include:
- locating the correct table
- extracting rows and columns
- building a Pandas DataFrame

In [55]:
url = "https://en.wikipedia.org/wiki/World_population"

In [56]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/91.0.4472.124 Safari/537.36"
}

In [57]:
data = requests.get(url, headers=headers)

In [58]:
soup = BeautifulSoup(data.text, "html.parser")

In [59]:
tables = soup.find_all('table')
len(tables)

26

In [60]:
for index, table in enumerate(tables):
    if ("10 most densely populated countries" in str(table)):
        table_index = index

print(table_index)

5

In [61]:
population_data = pd.DataFrame(columns=["Rank", "Country", "Population", "Area", "Density"])

In [62]:
for row in tables[table_index].tbody.find_all("tr"):
    col = row.find_all("td")

    if col:
        rank = col[0].text.strip()
        country = col[1].text.strip()
        population = col[2].text.strip()
        area = col[3].text.strip()
        density = col[4].text.strip()

        new_row = pd.DataFrame([{
            "Rank": rank,
            "Country": country,
            "Population": population,
            "Area": area,
            "Density": density
        }])

        population_data = pd.concat([population_data, new_row], ignore_index=True)

In [63]:
population_data

  Rank                 Country     Population       Area Density
0    1               Singapore      5,921,231        719   8,235
1    2              Bangladesh    165,650,475    148,460   1,116
2    3  Palestine[note 3][103]      5,223,000      6,025     867
3    4          Taiwan[note 4]     23,580,712     35,980     655
4    5             South Korea     51,844,834     99,720     520
5    6                 Lebanon      5,296,814     10,400     509
6    7                  Rwanda     13,173,730     26,338     500
7    8                 Burundi     12,696,478     27,830     456
8    9                  Israel      9,402,617     21,937     429
9   10                   India  1,389,637,446  3,287,263     423

In [66]:
from io import StringIO

## Using Pandas read_html()

Instead of manually parsing HTML, we can use `read_html()` to directly convert tables into DataFrames.

In [67]:
pd.read_html(StringIO(str(tables[table_index])), flavor='bs4')

[   Rank                 Country  Population  Area (km2)  Density (pop/km2)
 0     1               Singapore     5921231         719               8235
 1     2              Bangladesh   165650475      148460               1116
 2     3  Palestine[note 3][103]     5223000        6025                867
 3     4          Taiwan[note 4]    23580712       35980                655
 4     5             South Korea    51844834       99720                520
 5     6                 Lebanon     5296814       10400                509
 6     7                  Rwanda    13173730       26338                500
 7     8                 Burundi    12696478       27830                456
 8     9                  Israel     9402617       21937                429
 9    10                   India  1389637446     3287263                423]

In [68]:
population_data_read_html = pd.read_html(StringIO(str(tables[table_index])), flavor='bs4')[0]

In [69]:
population_data_read_html

   Rank                 Country  Population  Area (km2)  Density (pop/km2)
0     1               Singapore     5921231         719               8235
1     2              Bangladesh   165650475      148460               1116
2     3  Palestine[note 3][103]     5223000        6025                867
3     4          Taiwan[note 4]    23580712       35980                655
4     5             South Korea    51844834       99720                520
5     6                 Lebanon     5296814       10400                509
6     7                  Rwanda    13173730       26338                500
7     8                 Burundi    12696478       27830                456
8     9                  Israel     9402617       21937                429
9    10                   India  1389637446     3287263                423

In [70]:
dataframe_list = pd.read_html(StringIO(data.text), flavor='bs4')

In [71]:
len(dataframe_list)

26

In [72]:
dataframe_list[table_index]

   Rank                 Country  Population  Area (km2)  Density (pop/km2)
0     1               Singapore     5921231         719               8235
1     2              Bangladesh   165650475      148460               1116
2     3  Palestine[note 3][103]     5223000        6025                867
3     4          Taiwan[note 4]    23580712       35980                655
4     5             South Korea    51844834       99720                520
5     6                 Lebanon     5296814       10400                509
6     7                  Rwanda    13173730       26338                500
7     8                 Burundi    12696478       27830                456
8     9                  Israel     9402617       21937                429
9    10                   India  1389637446     3287263                423

In [73]:
heading = soup.find("h3", {"id": "Most_densely_populated_countries"})
heading

In [74]:
table = heading.find_next("table")
table

<table class="wikitable sortable" style="text-align:right">
<caption>10 most densely populated countries <small>(with population above 5 million)</small><sup class="reference" id="cite_ref-:10_107-0"><a href="#cite_note-:10-107"><span class="cite-bracket">[</span>102<span class="cite-bracket">]</span></a></sup>
</caption>
<tbody><tr>
<th scope="col">Rank
</th>
<th scope="col">Country
</th>
<th scope="col">Population
</th>
<th scope="col">Area<br/><small>(km<sup>2</sup>)</small>
</th>
<th scope="col">Density<br/><small>(pop/km<sup>2</sup>)</small>
</th></tr>
<tr>
<td>1</td>
<td align="left"><span class="flagicon nowrap"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/40px-Flag_of_Singapore.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/60px-Flag_of_Singapore.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Singapore" title="Singapore">Singapore</a></td>
<td>5,921,231</td>
<td>719</td>
<td>8,235
</td></tr>
<tr>
<td>2</td>
<td align="left"><span class="flagicon nowrap"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="307" data-file-width="512" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/40px-Flag_of_Bangladesh.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/60px-Flag_of_Bangladesh.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Bangladesh" title="Bangladesh">Bangladesh</a></td>
<td>165,650,475</td>
<td>148,460</td>
<td>1,116
</td></tr>
<tr>
<td>3</td>
<td align="left">
<p><span class="flagicon nowrap"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/40px-Flag_of_Palestine.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/60px-Flag_of_Palestine.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Palestine" title="Palestine">Palestine</a><sup class="reference" id="cite_ref-108"><a href="#cite_note-108"><span class="cite-bracket">[</span>note 3<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-109"><a href="#cite_note-109"><span class="cite-bracket">[</span>103<span class="cite-bracket">]</span></a></sup>
</p>
</td>
<td>5,223,000</td>
<td>6,025</td>
<td>867
</td></tr>
<tr>
<td>4</td>
<td align="left"><span class="flagicon nowrap"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/40px-Flag_of_the_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/60px-Flag_of_the_Republic_of_China.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Taiwan" title="Taiwan">Taiwan</a><sup class="reference" id="cite_ref-110"><a href="#cite_note-110"><span class="cite-bracket">[</span>note 4<span class="cite-bracket">]</span></a></sup></td>
<td>23,580,712</td>
<td>35,980</td>
<td>655
</td></tr>
<tr>
<td>5</td>
<td align="left"><span class="flagicon nowrap"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/40px-Flag_of_South_Korea.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/60px-Flag_of_South_Korea.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/South_Korea" title="South Korea">South Korea</a></td>
<td>51,844,834</td>
<td>99,720</td>
<td>520
</td></tr>
<tr>
<td>6</td>
<td align="left"><span class="flagicon nowrap"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="1920" data-file-width="2880" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/40px-Flag_of_Lebanon.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/60px-Flag_of_Lebanon.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Lebanon" title="Lebanon">Lebanon</a></td>
<td>5,296,814</td>
<td>10,400</td>
<td>509
</td></tr>
<tr>
<td>7</td>
<td align="left"><span class="flagicon nowrap"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/40px-Flag_of_Rwanda.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/60px-Flag_of_Rwanda.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Rwanda" title="Rwanda">Rwanda</a></td>
<td>13,173,730</td>
<td>26,338</td>
<td>500
</td></tr>
<tr>
<td>8</td>
<td align="left"><span class="flagicon nowrap"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1000" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/40px-Flag_of_Burundi.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/60px-Flag_of_Burundi.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Burundi" title="Burundi">Burundi</a></td>
<td>12,696,478</td>
<td>27,830</td>
<td>456
</td></tr>
<tr>
<td>9</td>
<td align="left"><span class="flagicon nowrap"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="800" data-file-width="1100" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/40px-Flag_of_Israel.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/60px-Flag_of_Israel.svg.png 2x" width="21"/></span></span> </span><a href="/wiki/Israel" title="Israel">Israel</a></td>
<td>9,402,617</td>
<td>21,937</td>
<td>429
</td></tr>
<tr>
<td>10</td>
<td align="left"><span class="flagicon nowrap"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/40px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/60px-Flag_of_India.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/India" title="India">India</a></td>
<td>1,389,637,446</td>
<td>3,287,263</td>
<td>423
</td></tr></tbody></table>

In [75]:
df = pd.read_html(StringIO(str(table)))[0]
print(df.head())

   Rank                 Country  Population  Area (km2)  Density (pop/km2)
0     1               Singapore     5921231         719               8235
1     2              Bangladesh   165650475      148460               1116
2     3  Palestine[note 3][103]     5223000        6025                867
3     4          Taiwan[note 4]    23580712       35980                655
4     5             South Korea    51844834       99720                520

## Key Takeaways

Summary of the main concepts demonstrated in this notebook.

- HTML can be parsed...
- BeautifulSoup enables...
- Pandas simplifies...
- Web scraping is...